name: ForraNova Cloud Factory
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Install Tools
        run: |
          npm install @capacitor/core @capacitor/cli @capacitor/android @capacitor/assets
          
      - name: Create Android Project
        run: |
          npx cap add android
          
      - name: Generate Shield Icon & Splash
        run: |
          npx @capacitor/assets generate --android --assetPath resources

      - name: Sync Web Code
        run: npx cap sync android

      - name: Build Official APK
        run: |
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug

      - name: Upload ForraNova APK
        uses: actions/upload-artifact@v4
        with:
          name: ForraNova-Academy-v1
          path: android/app/build/outputs/apk/debug/app-debug.apk
